#!/usr/bin/env sh

echo $1

npm run yaml;
resume export resume.html -t $1
npm run minify;

# rename plublications to projects
sed -i '' 's/publications/projects/g' index.html
sed -i '' 's/Publications/Projects/g' index.html
